name: Test Project
on: [push, workflow_dispatch] # run on push and manual trigger
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
        needs: test # topology test first then deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with: # configure the node version to use
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy
              run: echo "Deploying..."
